"""empty message

Revision ID: 05498f00b13f
Revises: 021c62fda1d4
Create Date: 2024-01-21 17:56:41.137421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05498f00b13f'
down_revision = '021c62fda1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_compliments_reciever_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_compliments_receiver_id_users'), 'users', ['receiver_id'], ['user_id'])
        batch_op.drop_column('reciever_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reciever_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_compliments_receiver_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_compliments_reciever_id_users', 'users', ['reciever_id'], ['user_id'])
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
