"""empty message

Revision ID: 2d3943a8a9d2
Revises: 
Create Date: 2024-01-22 12:59:11.895207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3943a8a9d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('compliments',
    sa.Column('compliment_id', sa.Integer(), nullable=False),
    sa.Column('compliment_text', sa.String(), nullable=True),
    sa.Column('date_sent', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], name=op.f('fk_compliments_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('fk_compliments_sender_id_users')),
    sa.PrimaryKeyConstraint('compliment_id')
    )
    op.create_table('hearts',
    sa.Column('heart_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('compliment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compliment_id'], ['compliments.compliment_id'], name=op.f('fk_hearts_compliment_id_compliments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_hearts_user_id_users')),
    sa.PrimaryKeyConstraint('heart_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hearts')
    op.drop_table('compliments')
    op.drop_table('users')
    # ### end Alembic commands ###
