"""empty message

Revision ID: b23319352ee9
Revises: 2d3943a8a9d2
Create Date: 2024-01-22 15:28:02.302515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23319352ee9'
down_revision = '2d3943a8a9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hearts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hearts_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hearts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_hearts_user_id_users', 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
